//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PW_PersonTeams
    {
        public System.Guid PersonTeamID { get; set; }
        public System.Guid PersonID { get; set; }
        public Nullable<System.Guid> TeamID { get; set; }
        public Nullable<System.Guid> LeaderID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public bool IsActive { get; set; }
    }
}
