//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PW_QuizTags
    {
        public System.Guid QuizTagID { get; set; }
        public System.Guid QuestionID { get; set; }
        public System.Guid SubjectID { get; set; }
        public bool IsActive { get; set; }
    }
}
